import type { Product } from "@/types";

export const PRODUCTS: Product[] = [
  // Val M Beauty - Walaky, Girly, Olé, Fresa Morada
  {
    id: "valm-walaky-1",
    brand: "valm-beauty",
    name: "Walaky - Exfoliante de Café",
    description:
      "Exfoliante para cuero cabelludo con café. Infaltable para mantener tu cuero cabelludo sano y que tu cabello crezca hermoso y sano. Aromas frescos que despiertan.",
    price: 45000,
    image: "/products/valm/valm_beauty_mzl_DUCSgsDDavs_1.jpg",
    category: "Walaky",
    stock: 15,
    weight: 200,
    dimensions: { width: 8, height: 18, length: 6 },
  },
  {
    id: "valm-walaky-2",
    brand: "valm-beauty",
    name: "Walaky - Fragancias Dulces",
    description:
      "Productos Walaky con aromas dulces que abrazan. Gel de ducha, crema corporal y más. Encuéntralos en coco-vainilla, floral y cálido.",
    price: 35000,
    image: "/products/valm/valm_beauty_mzl_DUCSgsDDavs_2.jpg",
    category: "Walaky",
    stock: 20,
    weight: 250,
    dimensions: { width: 8, height: 20, length: 6 },
  },
  {
    id: "valm-walaky-3",
    brand: "valm-beauty",
    name: "Walaky - Línea Floral",
    description:
      "Aromas florales que enamoran. Productos para el cuidado del cabello con fragancias frescas y delicadas.",
    price: 38000,
    image: "/products/valm/valm_beauty_mzl_DUCSgsDDavs_3.jpg",
    category: "Walaky",
    stock: 18,
    weight: 220,
    dimensions: { width: 8, height: 19, length: 6 },
  },
  {
    id: "valm-walaky-4",
    brand: "valm-beauty",
    name: "Walaky - Aromas Cálidos",
    description:
      "Fragancias cálidas que se quedan. Línea completa para #MiMomentoWalaky - sentirte linda desde la raíz.",
    price: 42000,
    image: "/products/valm/valm_beauty_mzl_DUCSgsDDavs_4.jpg",
    category: "Walaky",
    stock: 12,
    weight: 230,
    dimensions: { width: 8, height: 19, length: 6 },
  },
  {
    id: "valm-ole",
    brand: "valm-beauty",
    name: "Olé - Cepillo Anti Enredos IntelliFlex",
    description:
      "Cepillo desenredante para cabello húmedo y seco. Tecnología de cerdas flexibles IntelliFlex que elimina nudos sin esfuerzo, sin halones ni quiebres.",
    price: 55000,
    image: "/products/valm/valm_beauty_mzl_DUCSgsDDavs_5.jpg",
    category: "Olé",
    stock: 10,
    weight: 150,
    dimensions: { width: 25, height: 5, length: 8 },
  },
  {
    id: "valm-girly",
    brand: "valm-beauty",
    name: "Girly - Rutina Skincare",
    description:
      "Productos Girly para una piel sana y hermosa. No te saltes pasos importantes en tu rutina de cuidado facial.",
    price: 89000,
    image: "/products/valm/valm_beauty_mzl_DUCSgsDDavs_6.jpg",
    category: "Girly",
    stock: 8,
    weight: 300,
    dimensions: { width: 10, height: 5, length: 15 },
  },
  {
    id: "valm-galletas",
    brand: "valm-beauty",
    name: "Perfumes Capilares Aroma Galletas",
    description:
      "Perfumes capilares sin alcohol con aromas inspirados en galletas. Tan ricos e irresistibles que no vas a querer dejar de oler tu cabello todo el día.",
    price: 32000,
    image: "/products/valm/valm_beauty_mzl_DUCSgsDDavs_1.jpg",
    category: "Perfumes",
    stock: 25,
    weight: 100,
    dimensions: { width: 5, height: 15, length: 5 },
  },
  {
    id: "valm-coco",
    brand: "valm-beauty",
    name: "Línea Coco y Vainilla",
    description:
      "Aroma paradisíaco: coco con dulzura de vainilla. Disponible en Gel de ducha, Crema corporal y Body Shimmer Mist.",
    price: 45000,
    image: "/products/valm/valm_beauty_mzl_DUCSgsDDavs_2.jpg",
    category: "Cuerpo",
    stock: 15,
    weight: 250,
    dimensions: { width: 8, height: 20, length: 6 },
  },
  {
    id: "valm-mantequilla",
    brand: "valm-beauty",
    name: "Mantequilla Hidratante + Aceite Corporal",
    description:
      "Tu piel del cuerpo merece que la consientas. Paso 1: Mantequilla hidratante. Paso 2: Aceite corporal humectante.",
    price: 65000,
    image: "/products/valm/valm_beauty_mzl_DUCSgsDDavs_3.jpg",
    category: "Cuerpo",
    stock: 12,
    weight: 400,
    dimensions: { width: 10, height: 6, length: 20 },
  },
  // Click Hair
  {
    id: "click-perfume-1",
    brand: "click-hair",
    name: "Perfume Capilar - Rosa Seduction Flower",
    description:
      "Floral con toques frescos y dulces. Uno de los 7 aromas irresistibles de la línea Click Hair.",
    price: 35000,
    image: "/products/click/click_hair_manizales_DUQ_03SDvD__1.jpg",
    category: "Perfumes Capilares",
    stock: 20,
    weight: 100,
    dimensions: { width: 5, height: 15, length: 5 },
  },
  {
    id: "click-perfume-2",
    brand: "click-hair",
    name: "Perfume Capilar - Azul Candy Toy",
    description:
      "Dulce con notas frutales y amaderadas. Cabello que se ve, se siente y huele impecable.",
    price: 35000,
    image: "/products/click/click_hair_manizales_DUQ_03SDvD__2.jpg",
    category: "Perfumes Capilares",
    stock: 20,
    weight: 100,
    dimensions: { width: 5, height: 15, length: 5 },
  },
  {
    id: "click-perfume-3",
    brand: "click-hair",
    name: "Perfume Capilar - Morado Tropical Crush",
    description:
      "Frutal con un toque tropical y caramelo. Para las Click girls que aman destacar.",
    price: 35000,
    image: "/products/click/click_hair_manizales_DUQ_03SDvD__3.jpg",
    category: "Perfumes Capilares",
    stock: 18,
    weight: 100,
    dimensions: { width: 5, height: 15, length: 5 },
  },
  {
    id: "click-perfume-4",
    brand: "click-hair",
    name: "Perfume Capilar - Amarillo Fruit Explosion",
    description:
      "Exquisita mezcla de mango, vainilla, granada y rosas. 7 aromas para elegir tu favorito.",
    price: 35000,
    image: "/products/click/click_hair_manizales_DUQ_03SDvD__4.jpg",
    category: "Perfumes Capilares",
    stock: 18,
    weight: 100,
    dimensions: { width: 5, height: 15, length: 5 },
  },
  {
    id: "click-miel",
    brand: "click-hair",
    name: "Línea de Miel - Rutina Completa",
    description:
      "Oler a postre es de esas pequeñas felicidades. Rutina que se siente linda: cabello suave, brillante y oliendo delicioso.",
    price: 55000,
    image: "/products/click/click_hair_manizales_DT-1vljDs_t_1.jpg",
    category: "Click Hair",
    stock: 15,
    weight: 300,
    dimensions: { width: 8, height: 20, length: 6 },
  },
  {
    id: "click-mantequilla",
    brand: "click-hair",
    name: "Mantequilla Corporal con Glitter",
    description:
      "La mantequilla con más glitter de TODO COLOMBIA. Piel suave, luminosa e hidratada con un Glowy espectacular.",
    price: 45000,
    image: "/products/click/click_hair_manizales_DT-1vljDs_t_2.jpg",
    category: "Click Body",
    stock: 20,
    weight: 250,
    dimensions: { width: 8, height: 18, length: 6 },
  },
  {
    id: "click-masmelo",
    brand: "click-hair",
    name: "Perfume Miel y Masmelo",
    description:
      "Perfume para el cabello con aroma a miel y masmelo. ¿Cuál te gusta más: miel y masmelo o miel y pistacho?",
    price: 32000,
    image: "/products/click/click_hair_manizales_DT-1vljDs_t_3.jpg",
    category: "Perfumes Capilares",
    stock: 22,
    weight: 100,
    dimensions: { width: 5, height: 15, length: 5 },
  },
  {
    id: "click-pistacho",
    brand: "click-hair",
    name: "Perfume Miel y Pistacho",
    description:
      "Perfume para el cabello con aroma a miel y pistacho. Deliciosa combinación única.",
    price: 32000,
    image: "/products/click/click_hair_manizales_DT-1vljDs_t_4.jpg",
    category: "Perfumes Capilares",
    stock: 22,
    weight: 100,
    dimensions: { width: 5, height: 15, length: 5 },
  },
  {
    id: "click-kit",
    brand: "click-hair",
    name: "Kit Click Hair con Descuento",
    description:
      "Lleva tu kit antes de que suban los precios. Medios de pago: efectivo, tarjeta, ADDI. Envíos a toda Colombia.",
    price: 120000,
    image: "/products/click/click_hair_manizales_DT-1vljDs_t_5.jpg",
    category: "Kits",
    stock: 10,
    weight: 500,
    dimensions: { width: 15, height: 10, length: 25 },
  },
  {
    id: "click-barbie",
    brand: "click-hair",
    name: "Rutina Depilatoria Aroma Barbie",
    description:
      "Rutina depilatoria para una piel de bebé más suave, luminosa e hidratada. Aroma Barbie con Glowy espectacular.",
    price: 48000,
    image: "/products/click/click_hair_manizales_DUQ_03SDvD__1.jpg",
    category: "Click Body",
    stock: 15,
    weight: 300,
    dimensions: { width: 8, height: 20, length: 6 },
  },
];
